import './globals.css'
import styles from './layout.module.css'

import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1 className={styles.title}>🎀Next study🎀</h1>
        <nav className={styles.nav}>
          <a href='/'>home</a>
          <a href='/about'>about</a>
        </nav>
        {children}
        </body>
    </html>
  )
}
